### ISSUE TITLE
Try to clean up some errors showing up in logs

### ISSUE THREAD

**Issue by astump** [StarExec/StarExec#377]
In /project/tomcat-webapps/logs/starexec.log, there are quite a few errors getting generated.  Probably most of these have just accumulated over time.  It would be good to try to resolve some of them, if for no other reason than to reduce junk in the log files.

**Comment by gg9192** [comment]
First target that I can see being helpful to users:
24 Jul 11:49:06.554      pool-265-thread-4 [ERROR] - Error creating queue chart for all.q (1)

**Comment by gg9192** [comment]
This one can not be fixed, because the desired behavior of our api is to throw exception like this when something goes wrong.
24 Jul 12:20:30.133 http-nio-9880-exec-877 [ERROR] - failed to execute
org.starexec.exceptions.RESTException: null
	at org.starexec.exceptions.RESTException.<clinit>(RESTException.java:31)
	at org.starexec.app.RESTServices.getLoadsForQueue(RESTServices.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:252)
	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:217)
	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:206)
	at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:503)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:480)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:207)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:880)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1601)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)

**Comment by gg9192** [comment]
24 Jul 12:20:14.592      pool-280-thread-6 [ERROR] - removeJobFromDatabase24 Jul 13:10:10.479      pool-291-thread-3 [ERROR] - removeJobFromDatabase:Cannot delete or update a parent row: a foreign key constraint fails (`starexec_aguo2`.`runscript_errors`, CONSTRAINT `runscript_errors_job_pair_id` FOREIGN KEY (`job_pair_id`) REFERENCES `job_pairs` (`id`))
