### ISSUE TITLE
StarExec Command throws: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by fabeulous** [StarExec/StarExec#383]
When running  `getspacexml id=<spaceid> out=space.zip` the current version of StarExec Command throws the following exception:
```
StarCom> getspacexml id=<spaceid> out=space.zip
Processing your download request, please wait. This will take some time for large files
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.starexec.logger.BaseStarLogger.<init>(BaseStarLogger.java:17)
	at org.starexec.logger.StarLogger.<init>(StarLogger.java:16)
	at org.starexec.logger.StarLogger.getLogger(StarLogger.java:27)
	at org.starexec.util.Validator.<clinit>(Validator.java:17)
	at org.starexec.command.CommandValidator.isValidDownloadRequest(CommandValidator.java:197)
	at org.starexec.command.ArgumentParser.downloadArchive(ArgumentParser.java:442)
	at org.starexec.command.CommandParser.handleGetCommand(CommandParser.java:973)
	at org.starexec.command.CommandParser.parseCommand(CommandParser.java:724)
	at org.starexec.command.Shell.runShell(Shell.java:41)
	at org.starexec.command.Shell.main(Shell.java:70)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 10 more
```
It looks like the slf4j dependency is missing in the jar and/or archive.

**Comment by astump** [comment]
Hi, Fabian.  Thanks for reporting this issue.  We had to port off an old logging library, and it looks like we did not get this patched up correctly for StarExecCommand.  I will investigate and try to fix soon.  As you note, it might be as simple as just adding the proper dependency for the logging library, to the jar for StarExecCommand.  

Do you need this functionality restored quickly?  For example, is this for CoCo or TermCOMP?

**Comment by fabeulous** [comment]
Hi Aaron,
Thanks for the quick response. We do use StarExecCommand for CoCo, but last year's version of the jar seems to be working without an issue. We can just keep using that until this is fixed, so there is no hurry on our side.

**Comment by astump** [comment]
Ok, this is a relief, Fabian.  If you can just use last year's version of the jar for now, that will be good.  I will investigate the issue, naturally, but I am happy to know there is no emergency if I cannot take care of it right away.
