### ISSUE TITLE
Pause Job says Connection has already been closed.

### ISSUE THREAD

**Issue by pathawks** [StarExec/StarExec#61]
https://github.com/StarExec/StarExec/blob/4c3d481ffcbd7e19a6169f864bf33c44548b052b/src/org/starexec/data/database/Jobs.java#L4044-L4065

It seems that, by the time `pause` gets to line `4065`, the database connection has been closed.

```text
Level: ERROR
(org.starexec.data.database.Jobs) - Pause Job says Connection has already been closed.
Stack Trace:
java.sql.SQLException: Connection has already been closed.
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:118)
        at com.sun.proxy.$Proxy87.prepareCall(Unknown Source)
        at org.starexec.data.database.Common.queryUsingConnection(Common.java:366)
        at org.starexec.data.database.Jobs.getPairsHelper(Jobs.java:1420)
        at org.starexec.data.database.Jobs.getRunningPairs(Jobs.java:3547)
        at org.starexec.data.database.Jobs.pause(Jobs.java:4065)
        at org.starexec.data.database.Jobs.pause(Jobs.java:4025)
        at org.starexec.app.RESTServices.pauseJob(RESTServices.java:3702)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
        at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:252)
        at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:217)
        at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:206)
        at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:503)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:480)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:207)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by pathawks** [comment]
There is a call to `Jobs.getEnqueuedPairs` in line 4060 which queries the database without throwing an error. It seems the connection is closed some time after this?

https://github.com/StarExec/StarExec/blob/4c3d481ffcbd7e19a6169f864bf33c44548b052b/src/org/starexec/data/database/Jobs.java#L1440-L1443

`Jobs.getEnqueuedPairs` calls `getPairsHelper`.

https://github.com/StarExec/StarExec/blob/4c3d481ffcbd7e19a6169f864bf33c44548b052b/src/org/starexec/data/database/Jobs.java#L1419-L1430

`getPairsHelper` is using `Common.queryUsingConnection`.
